config/routes.rb
PunchIt::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :user_activities, only: [:index, :show, :create]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :status, only: [:create]
  root to: "sessions#new"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user

  attr_accessible :description, :is_in

  def checked_in?
    self.is_in ? true : false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :activities
  has_one :latest_activity,
   class_name: "Activity",
   order: "created_at DESC", 
   conditions: ["created_at >= ?", Time.now.beginning_of_day]

  attr_accessible :username, :email, :password, :password_confirmation
  validates_confirmation_of :password

  validates_uniqueness_of :username, :email 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = login(params[:username], params[:password])
    if user
      redirect_back_or_to user_activities_path notice: "Welcome #{user.username}!"
    else
      flash.now.alert = "Username or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url  notice: "Logged out!"
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def create
    StatusUpdateService.update(params[:status_update_service].merge(user: current_user))
    redirect_to user_activities_path
  end
end

app/controllers/user_activities_controller.rb
class UserActivitiesController < ApplicationController
  before_filter :require_login
  def index
    @status_update = StatusUpdateService.new(user: current_user )
    @users = User.where("id > 0").includes(:latest_activity)
    @users = @users.order("username ASC")
  end

  def show
  end

  def create
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash.now[:alert] = "Signed up"
      auto_login @user
      redirect_to user_activities_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/user_activities_helper.rb
module UserActivitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title PunchIT!
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 
  %body
    - if current_user
      #login_header
        = current_user.username
        = link_to "logout", logout_path
    #container
      #header
        %h1 PunchIT!
        %span.subheading Who's at their desk?
     
      #content.cf
        = yield

app/views/user_activities/_form.html.haml
= form_for @status_update, class: :status_update_form, url: status_path(current_user) do |f|
  = f.text_field :status
  = f.submit "update"

  %span.info Update your status with "IN description" or "OUT description". You can also include others by adding "with: person1, person2" to the end.

app/views/user_activities/create.html.haml
%h1 UserActivities#create
%p Find me in app/views/user_activities/create.html.haml

app/views/user_activities/index.html.haml
%section.post_update
  = render partial: 'form'

.user_activity.head
  .field Username
  .field Status
  .field Description
  .field When
  
- UserPresenter.present_each(@users, current_user) do |user|
  .user_activity.body
    .field.username= user.username
    .field.current_status= user.current_status
    .field.description= user.status_description
    .field.when=  user.status_time_ago

app/views/user_activities/show.html.haml
%h1 UserActivities#show
%p Find me in app/views/user_activities/show.html.haml

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/new.html.haml
= form_for @user do |f|
  - if @user.errors.any? 
    .error_messages
      %h3 Form is invalid
      %ul
        - for message in @user.errors.full_messages 
          %li= message 
      
  .field
    =f.label :username
    =f.text_field :username

  .field
    =f.label :email
    =f.text_field :email

  .field
    =f.label :pasword
    =f.password_field :password

  .field
    =f.label :password_confirmation
    =f.password_field :password_confirmation

  =f.submit "Sign up!"